### PR TITLE
Added unique country flag to data.json and updated readme

### PR DESCRIPTION
**Pull request by pswartz66**
Made three changes to my original PR:

1) updated the webscraper to use axios for http request
2) updated the readme to reflect the countries flags
3) updated the original data.json file with the *new data

### CODE REVIEW

**Comment by bhatvikrant** [comment]
Hey @pswartz66 , thanks for the effort man! Sorry for the delay,  I will review your PR this weekend and merge it into master. Keep up the good work!

**Comment by pswartz66** [comment]
@bhatvikrant Did you ever get a chance to look at this? Still showing as open, just wondering if there were any issues with my pr.

**Comment by sudo-kaizen** [comment]
@pswartz66 Awesome work on the flag thing! It never even crossed my mind while thinking of unique things

**Comment by bhatvikrant** [comment]
@pswartz66 thanks for bringing this to my notice again. I ll review it.

**Comment by bhatvikrant** [comment]
@pswartz66 there are some conflicts with the master branch. Can you please resolve them?

**Comment by pswartz66** [comment]
@bhatvikrant I fixed the conflicts, was mainly just the fact that I added "flag" to the countries listed in the readme. Should be good now. Let me know if you run into further issues.

**Pull request merged**
