### PR TITLE
Added phone codes

### PR DESCRIPTION
**Pull request by pf0**
I added the phone code for each country. The codes are from: https://countrycode.org/.

### CODE REVIEW

**Comment by mehulfollytobevice** [comment]
I have added all the codes of all the countries , please review my changes .

**Comment by bhatvikrant** [comment]
Great Work @pf0 ! It would be awesome if you could star this repository ⭐️. It would really help me to reach more developers 😇.

**Comment by Levi-Thieme** [comment]
The tests were not updated when you added the phone codes, so some of them broke...

**Comment by bhatvikrant** [comment]
oh snap! that slipped out of my mind. Can you fix them? @Levi-Thieme . I ll take them into consideration from now onwards.

**Pull request merged**
