### PR TITLE
Added phone code of all countries in the Json array

### LINKED ISSUE #15: Add phone code of all countries in data.json
For eg: 
```javascript
{
        country: "india",
        capital: "new delhi",
        currency: "indian rupee",
        native_language: ["hindi", "english"],
        phone_code: '+91'
    }
```

### PR DESCRIPTION
**Pull request by mehulfollytobevice**
Fixes #15 

I have added all the phone codes of all the countries in the Json array, kindly review my changes.

image

### CODE REVIEW

**Comment by bhatvikrant** [comment]
Great work @mehulfollytobevice , but Please maintain the original order of items in data.json file and then add phone_code in the end of each country object.

**Comment by bhatvikrant** [comment]
@mehulfollytobevice  It would be awesome if you could star this repository ⭐️. It would really help me to reach more developers 😇.

**Comment by mehulfollytobevice** [comment]
Hey , I have made all the changes as you suggested . Kindly review the changes and approve the pull request.

**Comment by bhatvikrant** [comment]
Hey, can you please resolve the conflicts with the master branch. :)

**Comment by mehulfollytobevice** [comment]
Hey .I  will just close this pull request,it  might resolve the issue

**Pull request closed without merging**
